### ISSUE TITLE
Design System Structure 

### ISSUE THREAD

**Issue by misterguerrero** [konstellation-io/kre#197]
### Tasks 
- [ ] @misterguerrero @mgs95 Define de structure to the first release of the Design System DOCZ
- [ ] @mgs95 Create a simple 10 mins video "How to install and work in DOCZ with Visual Studio"
- [ ] @jonasdacruz Validate the structure

### Initial and simplificated structure
![image](https://user-images.githubusercontent.com/23497637/87661226-8cb9dc00-c760-11ea-8ad8-41f942ea8b61.png)

**Comment by guumaster** [comment]
done
